[profile.default]
root = "."
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 999999
via_ir = true
fs_permissions = [
  { access = "read", path = "$DATA_DIR/" },
  { access = "read-write", path = "$REPO_DIR/pipeline_f/broadcast/" }
]
