[package]
name = "zk-circuit"
version.workspace = true
edition.workspace = true

[dependencies]
plonky2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
unicode-normalization = { workspace = true }
itertools = { workspace = true }
num = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
